
project_id = "dhgseybgaswdryynnomz"

[functions.create-application]
verify_jwt = false

[functions.process-dbops]
verify_jwt = false

[functions.process-bulk-data]
verify_jwt = false


[functions.validate-token]
verify_jwt = false
